package com.ticketrush.global.auth;

public enum AuthErrorCode {
    AUTH_ACCESS_TOKEN_REQUIRED,
    AUTH_TOKEN_EXPIRED,
    AUTH_TOKEN_INVALID,
    AUTH_ACCESS_TOKEN_REVOKED,
    AUTH_REFRESH_TOKEN_REQUIRED,
    AUTH_REFRESH_TOKEN_NOT_FOUND,
    AUTH_REFRESH_TOKEN_EXPIRED_OR_REVOKED,
    AUTH_REFRESH_TOKEN_USER_MISMATCH,
    AUTH_REFRESH_TOKEN_TYPE_INVALID,
    AUTH_ACCESS_TOKEN_TYPE_INVALID,
    AUTH_LOGOUT_TOKEN_USER_MISMATCH,
    AUTH_AUTHENTICATED_USER_REQUIRED,
    AUTH_USER_NOT_FOUND,
    AUTH_REQUEST_BODY_INVALID,
    AUTH_UNAUTHORIZED,
    AUTH_FORBIDDEN
}
